package com.adventOfCode.y2022;

import java.util.Arrays;

public class Day02 {

    public static final String TEST_INPUT = """
            A Y
            B X
            C Z""";

    public static final String INPUT = """
            A Y
            B Y
            B Z
            B Z
            A Y
            C Y
            A Y
            C Y
            A Y
            B X
            B Y
            B Z
            A Y
            A Y
            C Y
            C Y
            A Y
            C Y
            B Y
            A Y
            A Y
            C Y
            C X
            A Y
            B Z
            C Y
            A Y
            C Y
            A Y
            C Y
            A Z
            A Y
            C Y
            B Y
            A Y
            C Y
            B X
            B Z
            C X
            B Z
            B X
            C Y
            B Z
            A Y
            C Y
            B X
            A Y
            A Z
            B Y
            C Y
            A X
            C X
            C Y
            C Y
            A Y
            C X
            A Y
            C X
            C Y
            C Y
            A Y
            C Y
            A Z
            A Y
            B Z
            A Y
            A Y
            B X
            A Y
            B Y
            A Y
            B X
            B Y
            C Y
            A Y
            B X
            A Y
            C X
            B Y
            A Y
            B Z
            C Y
            C Y
            B Y
            B Z
            B Z
            B Y
            B Y
            A Y
            A Y
            A Z
            C Y
            B X
            A Y
            B Y
            A Y
            B X
            C Y
            A Z
            C Y
            C Y
            A Y
            A Y
            C Y
            C Y
            B X
            A Y
            A Y
            B X
            A Y
            C Y
            B Z
            A Y
            B Z
            C Y
            C X
            C Y
            B Z
            C Y
            A Y
            A Y
            B Y
            C X
            A X
            B X
            A Y
            C Y
            C Y
            A Y
            A Y
            C Y
            C Y
            A Z
            B X
            C Y
            B X
            A Y
            C Y
            A Y
            A Z
            C Y
            A Y
            A Y
            A Y
            C Y
            B X
            C Y
            A Y
            A X
            C Y
            A Y
            B X
            C Y
            A Y
            A Y
            B Y
            A Y
            A Y
            C Y
            B Y
            B X
            A Y
            A Y
            B X
            A Y
            C Y
            A X
            C Y
            C Y
            A Y
            B Z
            A Y
            A Y
            C Y
            A Y
            A Y
            C Y
            A Z
            B Z
            A Y
            C Y
            B X
            B X
            A Y
            A Y
            C Y
            A Y
            A Y
            C Y
            B Z
            B Z
            B Y
            B Y
            A Y
            A Y
            A Y
            A Y
            A Y
            C X
            A Y
            A Y
            A Y
            B Z
            C Y
            A Y
            B Z
            A Y
            A Y
            A Y
            B Z
            A Z
            C X
            B X
            B Z
            B Y
            B Y
            C Y
            C Y
            B Y
            A Y
            C Y
            A Y
            A Y
            C Y
            B X
            A Y
            A X
            A Y
            A Y
            B Z
            C Z
            A Y
            B X
            C Y
            C Y
            A Y
            A Z
            A Y
            C Y
            C Y
            C Y
            A Y
            A Y
            C Y
            C Y
            A Y
            A Y
            A X
            A Y
            C Y
            B X
            B Z
            C Y
            A Y
            A X
            A Y
            C X
            C Y
            B Z
            B Y
            A Y
            C X
            C Y
            C Y
            C X
            C Y
            B X
            A Y
            A Y
            A Y
            A Z
            C Y
            A Y
            C Y
            A Y
            B Y
            C X
            A Y
            A Y
            A Y
            C Y
            B Z
            A Y
            C X
            B Y
            A Y
            B Z
            A Y
            C Y
            C Y
            A Y
            B Z
            C Y
            A Z
            C Y
            A Y
            B X
            A Y
            A Z
            A Z
            A Z
            C Y
            C Y
            A Z
            B Y
            A Z
            A Y
            C X
            C Y
            A Y
            A Y
            B Y
            A Y
            A Y
            A Y
            B Y
            C Y
            A Y
            C Y
            A Y
            C X
            A Y
            A Z
            A Y
            A Y
            A Y
            C Y
            A Y
            C Y
            A Y
            A Y
            C X
            A Y
            C Y
            B Z
            C Y
            A Y
            B Y
            A Z
            C Y
            B Y
            A Y
            A Y
            A Y
            A Y
            A Y
            B Z
            B Z
            B Z
            A X
            A Y
            B Z
            A Y
            A Y
            C Y
            C Y
            B Z
            A Y
            B X
            C Y
            A Y
            A Y
            B Y
            C Y
            B Z
            A Y
            A Y
            A Y
            B X
            B Y
            C Y
            A Y
            A Y
            B X
            A Y
            B Z
            C X
            C X
            A Y
            C Z
            C Y
            C Y
            A Z
            B Z
            C Y
            A Y
            A Y
            C Y
            C Y
            C Y
            A Y
            A X
            B Z
            A Y
            A Y
            B Y
            B Y
            C Y
            B Y
            B Y
            B Z
            C Y
            C Y
            B Y
            A Y
            C Y
            A Y
            A Y
            B Y
            A Y
            A X
            A Y
            B Y
            A Y
            B Y
            C Y
            A Y
            B Z
            A Y
            B Y
            A Y
            A Y
            C X
            C Y
            C X
            A Z
            C Z
            B Y
            B Y
            C Y
            B Y
            A Y
            A Y
            B Y
            C Y
            C Y
            C Y
            A Y
            B Z
            B X
            C Y
            C Y
            A Z
            A Z
            A Y
            A Y
            A Y
            B Y
            A Y
            B Y
            A Y
            B Z
            A Z
            B Y
            C Y
            C Y
            C Z
            B Z
            B Y
            B X
            A Y
            B X
            B X
            B Y
            C Y
            B Z
            A Y
            C Y
            A Y
            C Z
            B Y
            A Y
            A Y
            C Y
            B Y
            C Y
            B Y
            B Y
            A Y
            A Y
            A Z
            C X
            A Y
            A Y
            C Y
            A Y
            B Z
            A Y
            A Y
            A Y
            C Z
            C Y
            B Z
            C Y
            B Z
            A Y
            B Z
            B Y
            A Y
            B Y
            A Y
            A Y
            A Y
            A Y
            C Y
            C Y
            C Z
            B Y
            C Y
            C Y
            A Y
            A Z
            A Y
            B Z
            A Y
            C Y
            C Y
            A Y
            A Y
            A Y
            B Z
            A Z
            A Y
            A Y
            A Y
            A Y
            A Y
            B Z
            B Z
            A Y
            A Y
            B Z
            A Z
            A Z
            A Y
            B Y
            B Y
            B Z
            A Y
            B Z
            C Y
            B Z
            B Y
            A Y
            A Y
            C Y
            C Y
            C Y
            A Y
            A Y
            C Y
            C X
            C Y
            A Y
            B Z
            A Y
            B X
            B Y
            B Y
            B X
            A Y
            A Z
            C Y
            B Z
            C Y
            A Z
            A Y
            A Y
            A Y
            C Y
            C X
            A Y
            C Y
            A Y
            B Z
            C Y
            A Y
            B Z
            A Y
            C Y
            A Y
            C Y
            B Y
            C Y
            B X
            A Y
            A Z
            C Y
            A Y
            C X
            C Y
            A Y
            C Y
            A Y
            C Y
            A Z
            B Y
            A Y
            B Z
            C Y
            C Z
            A Y
            A Y
            A Z
            A Y
            A Y
            C Y
            B Y
            C Z
            A Y
            B Y
            C X
            B Z
            C Y
            C Y
            B Z
            B Z
            A Y
            B Y
            C Y
            B Y
            C Y
            B Y
            A Z
            C Y
            B Z
            A Y
            A Y
            C Y
            A Y
            B Z
            A Y
            A Y
            C Y
            C Y
            A Z
            A Y
            A X
            C Y
            B Y
            B Y
            B Z
            B Y
            B Y
            C Y
            A Y
            C Y
            A Y
            A Y
            B X
            C Y
            B X
            A Y
            A Y
            B Y
            B Z
            C Y
            A Y
            C Y
            A Y
            A Y
            C Y
            B Y
            C Y
            B Y
            B X
            C Y
            A Y
            A Y
            B Z
            B Y
            B Y
            A Y
            A Y
            A Y
            A Y
            A Y
            C Y
            A Y
            A Y
            C Y
            A Y
            B Y
            C Y
            A Y
            A Y
            A Y
            C Y
            A Y
            B Y
            B Y
            A Z
            A Y
            C Y
            B Y
            C Y
            A Z
            B Z
            A X
            B Y
            B Z
            A Y
            A Y
            C Y
            B Y
            A Y
            B Z
            A Z
            C Y
            C Y
            A Y
            B X
            C Y
            A Y
            C Y
            C Y
            B Z
            A Y
            A Y
            A Y
            C Y
            A Y
            C Y
            B Y
            B Y
            B Y
            A Z
            C X
            B X
            C Y
            A Y
            A Y
            A Y
            A Y
            C Y
            A Y
            B Y
            A Y
            C Z
            C Y
            A Z
            B Y
            A Y
            C Z
            C X
            B Y
            C X
            A Y
            B Z
            A X
            B Y
            B Y
            B X
            C X
            A Z
            C Y
            B Y
            C Y
            A Z
            C Y
            C Y
            C Y
            A Y
            A Y
            A Y
            C Y
            A Y
            A Y
            C X
            B Z
            C Y
            C Y
            B Z
            C Y
            B Y
            B Z
            A Y
            B X
            A Y
            C Y
            A Y
            A Y
            A Y
            A Y
            B Z
            C Y
            C Y
            B Z
            B Y
            C Y
            C Z
            C Y
            C Y
            B Y
            A Y
            A Y
            A Y
            A Z
            C Y
            A Y
            A Y
            C Y
            A Y
            A Y
            B Y
            A Y
            A X
            A Y
            A Z
            B Y
            C Y
            A Y
            A Y
            C Y
            A Y
            B Z
            B Z
            C Y
            C Y
            A Y
            A Y
            B Z
            B Z
            A Y
            B Y
            C Y
            A Y
            B Y
            C Y
            A Y
            C Y
            B X
            A Y
            A Y
            A Y
            A Y
            A Y
            B X
            C Y
            C Y
            B Y
            A Y
            C Y
            B Y
            C Z
            C Y
            B X
            C Y
            A Y
            C Y
            C Y
            C Y
            C Y
            B X
            A Y
            C Y
            A X
            A Y
            C X
            A X
            C X
            C Y
            A X
            C Y
            C Z
            C Y
            A Y
            A Y
            A Z
            C Y
            C Y
            B Z
            A Y
            C Y
            A Y
            A Y
            B Z
            C Z
            A Y
            A Y
            C Y
            A Y
            A Y
            B Y
            A X
            A Y
            B Z
            A X
            C Y
            B X
            A Y
            A Z
            C Y
            B Z
            B Y
            B Y
            A X
            A Z
            B Z
            C X
            C Y
            B X
            B Z
            C Y
            C Y
            C Y
            A Y
            C Y
            B X
            C Y
            A Y
            A Y
            A X
            C Z
            B Z
            C Z
            C Y
            B Y
            C Y
            A Y
            A Y
            C Y
            C Y
            B Y
            C Y
            C Y
            C Y
            A Y
            B X
            A Y
            B Y
            C Y
            B X
            C Y
            C Y
            B Y
            A Y
            B Y
            B Y
            C Y
            A Y
            B X
            C X
            C Y
            B X
            A Y
            A Y
            B Z
            B Y
            A Y
            B Y
            B Y
            A Z
            B X
            B Z
            C Y
            B Y
            C Y
            A Y
            A Y
            B X
            A Y
            C X
            B Y
            B Z
            B X
            C X
            C Y
            C X
            A Y
            C Y
            B Y
            B Y
            A Y
            B X
            C Y
            C Y
            B X
            B X
            C Y
            B Z
            B Y
            A Y
            C Y
            B X
            C Y
            A Y
            A Z
            A Y
            A Y
            C Y
            A Z
            A Y
            B Z
            A Y
            B Y
            B X
            B Z
            B Y
            C Y
            A Y
            A Y
            C X
            B Y
            A Y
            B Y
            A Y
            C Y
            C Y
            A Y
            B Y
            B Y
            B Y
            C Y
            A Y
            B Y
            B X
            B X
            A Y
            C Y
            C Y
            A Y
            A Y
            A Y
            A Z
            C Y
            A Y
            C Y
            A Y
            B Z
            C Y
            C X
            C Y
            A Y
            C X
            B Z
            C X
            A Y
            B X
            A Y
            C Z
            C X
            A X
            A Y
            C Y
            B X
            A X
            B Y
            A Y
            A Y
            A Y
            C X
            A Z
            B Z
            C Y
            A Y
            C Y
            C Y
            C X
            C Y
            B Y
            C Y
            B Z
            B Z
            C Y
            B Y
            A Y
            A Y
            A Y
            B Y
            C Y
            A Y
            A Y
            C Y
            B Y
            B Y
            C Y
            A X
            A Y
            A Y
            A Z
            A Y
            B Y
            C Y
            A Y
            A Y
            A Y
            C Y
            A Y
            B X
            A Y
            C Y
            A Y
            A Y
            B Z
            B Y
            B Z
            C Y
            A Y
            A Z
            A Y
            A Y
            B Y
            A Y
            C Y
            C Y
            A Y
            B Y
            C X
            B Z
            A Y
            C Y
            B X
            B Y
            C Y
            B Y
            C Z
            A Z
            A Y
            C Y
            A Y
            C Y
            C X
            A Y
            C Y
            B X
            C Y
            A Y
            A Y
            C Y
            A Z
            B X
            B Z
            A Y
            B Z
            B Y
            A Z
            B Y
            A Y
            C Y
            A Y
            C Y
            C Y
            A Y
            B Y
            C Y
            A Y
            A Y
            B X
            A Y
            A Y
            A Y
            C Y
            A Z
            B Y
            B X
            A Y
            B Y
            C Y
            A Y
            C Y
            A Z
            B X
            A Y
            A Y
            A Y
            A Z
            A Y
            B Y
            B Z
            B Z
            A Y
            A Z
            A Y
            B X
            A Y
            A Y
            A Y
            C Y
            A Y
            A Y
            A Z
            C Y
            A Y
            A Y
            B X
            B Y
            C Y
            B X
            C Y
            A Y
            B Y
            A Y
            C Y
            C Y
            C Y
            C Y
            A Y
            C Y
            C Y
            B Y
            A Y
            C Y
            A Y
            A Y
            B Y
            A Y
            B Y
            C X
            A Y
            A Y
            A Y
            C Y
            B Z
            C Y
            A X
            A Y
            A Z
            A Y
            B X
            C X
            A Y
            B Y
            A Y
            A Y
            B Y
            A Y
            C Y
            A Y
            A Y
            B Z
            C Y
            A Y
            A X
            B Z
            A Y
            A Y
            A Z
            C Y
            A Z
            C Y
            B Y
            A Y
            C X
            B X
            A Y
            C X
            C X
            A Y
            A Y
            A X
            A Y
            A Y
            A Y
            B Y
            C X
            A Y
            C Y
            C Y
            A Y
            B Z
            A Y
            C Y
            B Z
            A Y
            C Y
            C Y
            B X
            B Y
            B Z
            A Y
            C Z
            C Y
            A Y
            C X
            A Y
            C X
            B Z
            A Y
            B Y
            A Y
            C Y
            B Y
            A Y
            B Y
            B X
            A Y
            B Y
            C Y
            A Y
            C Y
            C Y
            A X
            C Y
            C X
            A X
            A Y
            C Y
            C Y
            C X
            C X
            C Y
            C Y
            C Y
            A Z
            A Y
            B Z
            C Y
            C Y
            A Z
            A Y
            A Y
            C X
            A Y
            A Y
            A Y
            C Y
            A Y
            C Y
            A Y
            A Y
            A Y
            C Y
            C Y
            A Y
            B Y
            B Y
            A Z
            B X
            B X
            B Y
            C Y
            A Y
            A X
            A Y
            B X
            C Y
            B X
            C X
            C Y
            A Y
            A Y
            C Y
            A Y
            C Y
            A Y
            B Z
            C Y
            A Y
            B Y
            A Y
            A Y
            A Y
            A Y
            A Z
            C Y
            A Y
            B Y
            C Y
            C Y
            A Y
            C X
            A Y
            A Y
            C Y
            C Y
            C X
            B Y
            A Y
            A Y
            A Y
            A Y
            C Y
            A Y
            B X
            A Z
            A Y
            C Y
            B X
            A Y
            C Y
            A Y
            A Y
            A Y
            C Y
            B Y
            A Y
            A Y
            B Z
            C Y
            C X
            A Y
            A Y
            C Y
            A Y
            C X
            C Y
            C Y
            A Y
            C Y
            C Y
            C Y
            C X
            A Y
            A Y
            A Y
            A Y
            C Y
            B Y
            C Y
            A Y
            A Z
            B Z
            A Y
            B Y
            B Z
            C Y
            A X
            B Y
            C Y
            A Y
            A Y
            C Y
            A Y
            A Y
            A Z
            B Z
            C X
            B Y
            B Y
            C Y
            C Y
            C Y
            A Y
            A Y
            A Y
            A Y
            C Z
            B Y
            B Z
            C Y
            C Y
            A Y
            B Y
            C Y
            A Y
            A X
            B X
            C Y
            A Y
            C Y
            C X
            C Y
            A Y
            A Y
            B Y
            B X
            A Y
            C Y
            A Z
            B X
            C Y
            B X
            A Y
            B Z
            A Y
            A Y
            B Y
            B Z
            B X
            A Y
            B X
            B Z
            A Y
            C Y
            A Y
            A Y
            A Z
            B X
            A Y
            A Y
            B Y
            A Y
            B Z
            B X
            C Y
            C X
            C X
            C X
            A X
            A Y
            A Y
            A Y
            B Y
            A Y
            A Y
            A Y
            C Y
            B Y
            B X
            B Y
            C Y
            A Z
            A Y
            B Z
            A Y
            C Y
            A Y
            A Z
            B Z
            C Y
            B Z
            A Y
            C Y
            B Y
            C Y
            A Y
            C Y
            B Z
            B Y
            B X
            C X
            A Y
            A X
            B X
            C Y
            C Y
            A Y
            C Y
            B Y
            A Y
            B Z
            A Y
            B X
            A Y
            C Y
            A Y
            C Y
            C Y
            A Y
            A Y
            A Y
            C X
            B Y
            B Z
            B Y
            A Y
            A Y
            A Z
            B X
            A Y
            A Z
            C Y
            B Z
            B X
            A Y
            C Y
            A Y
            B Z
            A Y
            A Z
            B Y
            C X
            A Y
            C Y
            C Y
            C Y
            C Y
            A Y
            A Y
            B Y
            A Y
            C Y
            A Y
            B Z
            C Y
            A Z
            C Y
            A Y
            A Z
            C Y
            B X
            C Y
            C Y
            A Y
            A Y
            B Z
            B Y
            B X
            A Y
            A Y
            B Y
            A Y
            A Y
            B X
            B Y
            A Y
            C Y
            A Y
            C Y
            C Y
            B Y
            B Y
            C Y
            A Y
            A Z
            A Y
            A Y
            A Y
            C Y
            C X
            B Z
            C Y
            A Y
            A Y
            C Y
            A Y
            A Y
            A Z
            C X
            C Y
            A Y
            A Y
            C Y
            C Y
            A Y
            A Y
            C Y
            C X
            A Y
            A Y
            B Y
            A Z
            B Y
            A Y
            B Z
            C Y
            C Y
            A Y
            B Y
            A Y
            C Y
            B Z
            A Y
            A Y
            C X
            C Y
            C X
            A Y
            A Y
            A Y
            B Y
            C X
            A Y
            B X
            B Y
            C Y
            A Y
            C Y
            A Y
            A Y
            C Y
            A Z
            A Y
            C X
            A Y
            A Y
            C Y
            C Y
            C X
            A Y
            A Y
            C Y
            B Y
            A Y
            C Y
            A Y
            B Z
            A Y
            C Y
            A Y
            A Y
            A Z
            A Y
            B Z
            A Y
            A Y
            A Y
            A Y
            A Y
            C Z
            C X
            A Y
            A Z
            C Y
            C Y
            B Z
            A Y
            B X
            A Y
            A Y
            A Z
            B Z
            A Y
            A Y
            C Y
            A Y
            C Y
            B Z
            B X
            C X
            A Y
            B Y
            C Y
            C X
            B Y
            C Y
            A Y
            A Y
            A Y
            A Z
            B Y
            A Y
            C Y
            A Y
            A Y
            A Y
            A Y
            C Y
            C Y
            A Y
            A Z
            C Y
            B Y
            C Y
            C Y
            B Y
            A Y
            C Y
            B Z
            A Y
            A Y
            B Z
            C Y
            B Z
            C Y
            C Y
            B Z
            B Y
            A Y
            C X
            C Y
            B Y
            A Y
            A Y
            A Y
            B Z
            A Y
            B Y
            A Y
            C Y
            A Y
            A Y
            C Y
            A Z
            A Y
            C Y
            B Y
            A Y
            B Z
            C Y
            A Y
            A Y
            C Y
            B Z
            B Z
            A Y
            A Y
            A Y
            A Y
            A Y
            C Y
            A Y
            A Y
            A Y
            A Y
            C Y
            A Y
            C Y
            B X
            B Y
            A Y
            C Z
            B Y
            C Y
            C Y
            A Y
            C Y
            C Y
            A Y
            A Y
            A Y
            A Y
            B X
            B Z
            C Y
            B X
            B Y
            B Y
            B Z
            B X
            A Y
            A Y
            B Y
            B X
            A Y
            A Y
            C Y
            C X
            A Y
            B Y
            A Y
            B Y
            B Y
            B Y
            C Y
            A Y
            A X
            A Y
            C Y
            B X
            B Y
            A Y
            A X
            C Y
            C X
            A Y
            A Y
            A Y
            B Y
            C X
            A Z
            B Z
            A Y
            B Z
            A Y
            A Y
            A Y
            A Y
            B X
            A Y
            C Z
            C Y
            C Y
            C Y
            B Z
            A Y
            A Y
            B Z
            B Y
            A Z
            A Y
            A Y
            B Z
            C Y
            A Y
            C Y
            C Y
            C Y
            B X
            B Y
            A Y
            A Y
            A Y
            A Y
            B Y
            A Y
            B Z
            B Z
            A Y
            C Y
            C Y
            C Y
            A Y
            C Y
            B Y
            C Y
            A Y
            B Y
            B Y
            B X
            C X
            A Y
            A Y
            A Y
            B Y
            C Y
            B Y
            C X
            B Y
            B Y
            A Z
            C Z
            C X
            B Y
            C Y
            B Y
            C Y
            B Z
            A Y
            C Y
            A Y
            B Y
            C Y
            A Y
            A Y
            C Z
            B X
            A Z
            C Y
            C Y
            A Y
            B Z
            B Y
            C X
            A Y
            B Z
            A Y
            A Y
            A X
            A Y
            B Y
            C Y
            B Y
            A Y
            A Y
            B Y
            C Y
            B Y
            A Y
            A Y
            B Y
            C Y
            B Y
            C Y
            B Y
            B Y
            B X
            A Y
            A Y
            C X
            A Y
            C Y
            B Z
            A Y
            B Y
            A Z
            A Y
            A Y
            B Y
            C Y
            B Z
            A Z
            A Y
            B Z
            C Y
            A Y
            A Y
            A Y
            C X
            C Y
            A Y
            C Y
            A Y
            A Y
            B Z
            A Y
            A Z
            C Y
            C Y
            A X
            C X
            A Y
            B Z
            A Y
            A Y
            B Y
            A Y
            A Y
            B Z
            A Y
            B Y
            B Z
            A Y
            A Z
            A Y
            A Z
            C Y
            B Y
            A Y
            A Y
            B Z
            C X
            C Y
            A Y
            A Y
            A Y
            A Y
            A Y
            A Z
            C Y
            B X
            A Z
            B Y
            A Y
            A Z
            A Y
            C X
            A Y
            A Y
            C Z
            B Y
            C Y
            C Y
            B Y
            C X
            A Y
            A Y
            B Y
            A Y
            A Y
            A Y
            B Y
            B Y
            C Y
            A Y
            A Y
            B Y
            B X
            A Y
            A Y
            C Y
            B Y
            C Y
            B Z
            A Z
            C X
            B X
            A Y
            A Y
            A Y
            C Z
            A Y
            C Y
            B Y
            A Y
            B X
            A Y
            C Y
            A Y
            B Y
            A Y
            B X
            B Y
            A Y
            C Y
            C Y
            A Y
            A Y
            A Y
            A Y
            C Y
            C Y
            A Y
            A Y
            B Y
            C Y
            B Z
            C Y
            C Y
            C Z
            A Z
            B X
            C Y
            A Y
            B Y
            B Y
            A Y
            B X
            A Y
            B Y
            B X
            C Y
            B X
            B Y
            B Y
            B Z
            A Y
            A Z
            B Z
            A X
            C Y
            B X
            C X
            A Y
            B Z
            A Y
            A Y
            A Z
            C X
            A Y
            B Y
            B Y
            A Y
            A Z
            A Y
            B X
            B X
            A Y
            B Y
            C Y
            A Y
            B X
            B Z
            B Z
            B Z
            C X
            A Y
            C Y
            A Z
            B Y
            B Y
            A Y
            B Y
            C Y
            A Y
            A Z
            B X
            C Y
            C Y
            A X
            C Y
            C Y
            B Y
            B X
            C X
            A Y
            C X
            C Y
            A Y
            B Y
            A Y
            A Y
            B Z
            C Y
            B X
            A X
            C Y
            B X
            C Y
            C Y
            A Y
            C Y
            C Y
            C X
            A Y
            A Y
            B Y
            C Y
            C Y
            A Y
            C Y
            A Z
            A Y
            A Y
            B X
            A Y
            A Y
            A Y
            A Y
            A Y
            C Y
            B Y
            B Y
            A Y
            A Y
            B Y
            C Y
            B Y
            A Y
            A Y
            B Z
            C X
            A Y
            C Y
            B Y
            B X
            A X
            A Y
            B Y
            B X
            B Y
            A Y
            C Y
            A Z
            B Y
            C Y
            C Y
            B Z
            C Y
            C Y
            C Y
            C Y
            C Y
            A Y
            B Z
            C Y
            C Y
            A Z
            A Y
            B Z
            A Y
            B X
            C Y
            C X
            A Y
            A Y
            B Y
            A Z
            A Y
            C Z
            A Y
            B Y
            A Y
            B X
            A Y
            B Z
            C Y
            A Y
            A Z
            A Y
            B Y
            A Y
            B Z
            A Y
            A Y
            A Y
            A Y
            C X
            A Y
            B Z
            A Y
            B Z
            B X
            A Y
            B Y
            C Y
            B Z
            B Z
            C Y
            B Z
            A Z
            A Z
            B Z
            A Y
            C Y
            C Y
            A Y
            C Y
            B X
            C Y
            C Y
            B Z
            A Y
            A Y
            C Y
            B Y
            A Y
            C Y
            C Y
            A Y
            B Y
            A Y
            B Y
            A Y
            A Y
            A Y
            C Y
            B X
            B X
            C Y
            C Y
            B X
            A Y
            C Y
            A Y
            B Z
            A Z
            A Y
            C Y
            A Y
            C Y
            A Y
            C Y
            C Y
            C Y
            A Z
            A Y
            C Y
            B Y
            A Y
            A Y
            C Y
            C Y
            A Y
            B X
            B Y
            C Y
            B Y
            B Z
            C Y
            A Y
            C Y
            C Y
            C Y
            A X
            A Y
            C X
            A Z
            C Y
            C Y
            A Y
            C Y
            A Y
            C Y
            A Y
            A Y
            C Y
            B Y
            A Y
            A Y
            A Y
            C Y
            C Z
            A Z
            A Y
            C Y
            A Y
            A Z
            C Y
            A Y
            C Y
            B Y
            A Y
            B Y
            C Y
            B Y
            A Y
            A Z
            A Y
            B X
            C X
            C Y
            B Z
            C Y
            C Y
            A Y
            B X
            B Z
            A Y
            B Z
            B X
            A Y
            A Y
            A Y
            B X
            C Y
            C Y
            C Y
            C Y
            B Z
            A Y
            B Y
            B Z
            A Y
            A Z
            A Y
            A Y
            A Y
            B Z
            C Y
            A Y
            A Y
            B Y
            C Y
            C X
            A Y
            C Y
            A Y
            A Y
            A Y
            C Z
            A Z
            B Y
            A Z
            B X
            B Y
            A X
            A Y
            A Y
            C Y
            C Y
            B X
            A Z
            C Y
            B Y
            C X
            A Y
            A Y
            B Y
            C Y
            C Y
            A Y
            C X
            A Y
            A Y
            A Y
            A Y
            C Y
            C Y
            A Y
            C Y
            A Z
            A Y
            C Y
            A Y
            B X
            C Y
            C Y
            C Y
            B X
            B Y
            A Y
            A Y
            A Y
            C Y
            A Y
            A Y
            B Y
            A Y
            A Y
            C Y
            C Y
            A Y
            C Y
            C Y
            C Y
            C Y
            C Y
            B Z
            C Z
            C Y
            B X
            B Y
            C Y
            A Y
            A Y
            A Y
            A Y
            B Z
            A Y
            A Z
            C X
            A X
            A Y
            A Y
            C X
            C Y
            B Y
            A Y
            C Z
            B Y
            B Y
            C Z
            C Z
            A Y
            A Y
            A Y
            C X
            B Y
            B Z
            A Y
            A Y
            B Y
            C X
            B Y
            A Y
            C Y
            B Y
            A Y
            """;

    public static void main(String[] args) {
        String[] strategyGuide = INPUT.split("\n");
        //Part 1
        int sum = testStrategy(strategyGuide);
        System.out.println(sum);

        //Part 2
        int sum2 = realStrategy(strategyGuide);
        System.out.println(sum2);
    }

    private static int realStrategy(String[] strategyGuide) {
        return Arrays.stream(strategyGuide)
                .mapToInt(round -> {
                    char opponent = round.charAt(0);
                    char result = round.charAt(2);
                    char me =
                            //Draw
                            result == 'Y' ? draw(opponent) :
                                    //Lose
                                    (result == 'X' ? lose(opponent):
                                            //Win
                                            win(opponent));
                    int a = me == 'X' ? 1 : (me == 'Y' ? 2 : 3);
                    int b = //Draw
                            result == 'Y' ? 3 :
                                    //Lose
                                    (result == 'X' ? 0:
                                            //Win
                                            6);
                    return a + b;
                })
                .sum();
    }

    private static char draw(char opponent) {
        return switch (opponent) {
            //Rock
            case 'A' -> 'X';//Rock
            //Paper
            case 'B' -> 'Y';//Paper
            //Scissors
            case 'C' -> 'Z';//Scissors
            default -> '0';
        };
    }

    private static char lose(char opponent) {
        return switch (opponent) {
            //Rock
            case 'A' -> 'Z';//Scissors
            //Paper
            case 'B' -> 'X';//Rock
            //Scissors
            case 'C' -> 'Y';//Paper
            default -> '0';
        };
    }

    private static char win(char opponent) {
        return switch (opponent) {
            //Rock
            case 'A' -> 'Y';//Paper
            //Paper
            case 'B' -> 'Z';//Scissors
            //Scissors
            case 'C' -> 'X';//Rock
            default -> '0';
        };
    }

    private static int testStrategy(String[] strategyGuide) {
        return Arrays.stream(strategyGuide)
                .mapToInt(round -> {
                    char opponent = round.charAt(0);
                    char me = round.charAt(2);
                    int a = me == 'X' ? 1 : (me == 'Y' ? 2 : 3);
                    int b = battle(opponent, me);
                    return a + b;
                })
                .sum();
    }

    public static int battle(char opponent, char me){
        return switch (me) {
            case 'X' -> opponent == 'A' ? 3 : (opponent == 'B' ? 0 : 6);
            case 'Y' -> opponent == 'B' ? 3 : (opponent == 'C' ? 0 : 6);
            case 'Z' -> opponent == 'C' ? 3 : (opponent == 'A' ? 0 : 6);
            default -> -1;
        };
    }

}
